-------------------------------------
------- Created by T1GER#9080 -------
------------------------------------- 

Lang = {
  ['dispatch_name']         	= '^5 Dispatch: ',
  ['police_notify']         	= '^0Ongoing BANK ROBBERY in ^1%s^0 at ^3%s^0',
  ['silent_alarm']         	  = '^0A silent alarm has been triggered in ^3%s',
  -- Drilling Draw Texts:
  ['safe_not_drilled']        = '~r~[E]~s~ | Drill Safe',
  ['safe_drilled']            = 'Safe ~g~[drilled]~s~',
  ['safe_destroyed']          = 'Safe ~r~[destroyed]~s~',
  ['safe_reward_txt']         = 'You found ~y~%sx~s~ %s',
  -- Drilling Texts:
  ['safe_destroyed_noti']     = 'This safe is ~r~destroyed',
  ['safe_arealdy_robbed']     = 'This safe is already ~g~robbed~s~!',
  ['you_destroyed_safe']      = 'You ~r~destroyed~s~ the safe!',
  ['drilling_paused']         = 'You ~y~stopped~s~ drilling',
  ['safe_drilled_by_ply']     = 'This safe is drilled by someone else.',
  ['drill_item_usable']       = 'Your drill is still usable',
  ['drill_item_not_usable']   = 'Your drill is not usable anymore',
  -- Bank Draw Texts:
  ['hack_keypad_1']           = '~r~[E]~s~ | Hack Keypad',
  ['open_keypad_1']           = '~y~[G]~s~ | Use Access Card',
  ['hack_keypad_2']           = '~r~[K]~s~ | Hack Keypad',
  ['open_keypad_2']           = '~y~[G]~s~ | Use Access Card',
  ['lockpick_desk_door']      = '~r~[E]~s~ | Lockpick Door',
  ['open_desk_door']          = '~r~[E]~s~ | Open Door',
  ['open_desk_door_pol']      = '~r~[E]~s~ | Open Door | ~r~[G]~s~ Secure Bank',
  ['close_desk_door']         = '~r~[E]~s~ | Close Door',
  ['close_desk_door_pol']     = '~r~[E]~s~ | Close Door | ~r~[G]~s~ Secure Bank',
  ['desk_cash_not_robbed']    = '~r~[E]~s~ | Rob Petty Cash',
  ['desk_cash_robbed']        = 'Cash ~g~[robbed]~s~',
  ['power_box_not_disabled']  = '~r~[E]~s~ | Disable Electric',
  ['power_box_disabled']      = 'Power Box ~r~[disabled]~s~',
  ['open_pacific_safe']       = '~r~[E]~s~ | Open Safe',
  ['pacific_safe_cracked']    = 'Safe ~g~[cracked]~s~',
  ['close_vault_dr']          = '~g~[E]~s~ | Close Vault Door',
  ['open_vault_dr']           = '~g~[E]~s~ | Open Vault Door',
  ['open_vault_dr_pol']       = '~g~[E]~s~ Open Vault Door | ~r~[G]~s~ Secure Vault',
  -- Bank Text:
  ['bank_in_lockdown']        = 'BANK IN LOCKDOWN',
  ['no_drill']                = 'You need a drill.',
  ['no_hacking_dev']          = 'You need a hacking device!',
  ['no_access_card']          = 'You need the access card from the safe.',
  ['no_lockpick']             = 'You need a lockpick!',
  ['no_hammerwirecutter']     = 'You need a Hammer & Wire Cutter',
  ['get_closer_to_door']      = 'Move closer to the door to interact.',
  ['vault_dr_must_close']     = 'You need to close the vault door first!',
  ['found_access_card']       = 'You found an access card in the safe.',
  ['hacker_dev_corrupted']    = 'Hacker Device got corrupted, no longer usable.',
  ['you_secured_bank']        = 'You secured the bank. All banks will be unlocked!',
  ['no_access_to_cam']        = 'You do not have access to security cameras.',
  ['notify_free_time']        = 'Electric is cutted. You have ~b~%s seconds~s~ until silent alarm is triggered.',
  ['extra_free_time_added']   = 'More time added. You now have: ~b~%s seconds~s~ until silent alarm is triggered.',
  -- Camera:
  ['camera_not_exist']        = 'Entered camera ID does not exist.',
  -- police:
  ['dispatch_name']         	= '^5 Dispatch: ',
  ['police_notify']         	= '^0Ongoing shootout and grand theft auto at ^3%s^0',
  -- Labs:
  ['drug_lab_interact']       = '~r~[E]~s~ | DRUG LAB',
  ['lab_owned_player']        = 'LAB NOT AVAILABLE',
  ['drug_lab_rob']            = '~r~[E]~s~ | ROB DRUG LAB',
  ['only_own_one_lab']        = 'YOU CAN ONLY OWN 1 DRUG LAB',
  ['press_to_buy_lab']        = '~r~[E]~s~ | BUY LAB ~g~[$%s]~s~',
  ['police_raid_lab']         = '~r~[E]~s~ | RAID LAB',
  ['press_to_leave_lab']      = '~r~[E]~s~ | EXIT DRUG LAB',
  ['not_enough_money']        = 'You do not have enough money.',
  ['drug_lab_purchased']      = 'You purchased a ~b~drug lab~s~ and paid ~g~$%s~s~',
  ['drug_lab_sold']           = 'You sold your ~b~drug lab~s~ and received ~g~$%s~s~',
  ['enter_drug_lab']          = 'Enter Lab',
  ['sell_drug_lab']           = 'Sell Lab',
  ['not_your_drug_lab']       = 'You cannot sell a drug lab, which you dont own',
  -- Menu Text:
  ['button_yes']         	    = 'Yes',
  ['button_no']         	    = 'No',
  ['button_return']         	= 'Return',
  -- Laptop
  ['press_to_use_laptop']     = '~r~[G]~s~ LAPTOP',
  ['prog_bar_using_laptop']   = 'USING LAPTOP',
  ['laptop_supplies']         = 'Supplies',
  ['laptop_stock']            = 'Stock',
  ['laptop_check_supplies']   = 'Check Supplies',
  ['laptop_buy_supplies']     = 'Buy Supplies',
  ['laptop_steal_supplies']   = 'Steal Supplies',
  ['laptop_check_stock']      = 'Check Stock',
  ['laptop_sell_stock']       = 'Sell Stock',
  ['laptop_cur_supplies']     = 'Current Supplies: %s',
  ['laptop_cur_stock']        = 'Current Stock: %s',
  ['laptop_pol_seize']        = 'Seize Supplies & Stock',
  ['laptop_rob_lab']          = 'Steal Supplies & Stock',
  ['supplies_level_msg']      = 'Supplies Level: %s',
  ['stock_level_msg']         = 'Stock Level: %s',
  ['supplies_purchased']      = 'You purchased ~b~%sx~s~ level of supplies and paid ~r~$%s~s~',
  ['supplies_are_full']       = 'You cannot purchase more supplies. Current supplies level is at maximum.',
  ['supplies_space_full']     = 'There is no space for more supplies right now. Try again later.',
  ['no_jobs_available']       = 'No ~y~jobs~s~ are currently available, please try again later!',
  ['already_in_job']          = 'You are already doing a job, finish that first!',
  ['laptop_stock_level']      = 'Stock Level: %s',
  ['laptop_sell_price']       = 'Sell Price: %s',
  ['laptop_find_buyer']       = 'Find Buyer for Stock',
  ['stock_is_empty']          = 'You have no stock to sell',
  ['no_available_buyers']     = 'No ~y~buyers~s~ are currently available, please try again later!',
  ['already_selling_stock']   = 'You already have a drug-trade with a buyer, finish that first!',
  -- Job:
  ['job_go_to_location']      = 'Go to ~y~%s~s~.',
  ['take_out_the_goons']      = 'Take out the ~r~goons~s~.',
  ['steal_the_supplies']      = 'Steal the ~r~vehicle~s~ with the ~b~supplies~s~.',
  ['press_to_steal']          = '~g~[G]~s~ to ~y~Steal~s~',
  ['press_to_deliver']        = '~g~[E]~s~ to ~y~Deliver~s~',
  ['progbar_stealing']        = 'STEALING VEHICLE',
  ['deliver_supplies_back']   = 'Deliver the ~b~Supplies~s~ to your ~y~Lab~s~.',
  ['veh_not_matching']        = 'The vehicle does not match the job vehicle?!',
  -- Stock Job:
  ['leave_drug_lab']          = 'Leave the ~g~Drug Lab~s~',
  ['get_in_vehicle']          = 'Enter the ~b~vehicle~s~',
  ['deliver_stock_drop_off']  = 'Deliver the ~b~Stock~s~ to the ~y~drop-off~s~',
  ['deliver_stock']           = '~g~[E]~s~ to ~y~Deliver~s~',
  ['stock_sold_success']      = 'You successfully sold your ~b~stock~s~ and got ~g~$%s~s~ cash',
  -- Robbery:
  ['lab_robbery_done']        = 'You successfully robbed the supplies and products from the lab!',
  ['lab_robbery_in_progress'] = 'Someone is ~b~attempting~s~ to access your ~g~drug lab~s~',
  ['lab_robbery_hack_fail']   = 'You failed the hacking.',
  ['prog_bar_pre_hack']       = 'PREPARING HACKING DEVICE',
  ['prog_bar_transfer']       = 'TRANSFERRING SUPPLIES & STOCK',
  -- Police Seizing:
  ['lab_raid_on_going']       = 'Police are ~r~raiding~s~ your ~g~drug lab~s~',
  ['prog_bar_raid_door']      = 'OPENING DOOR',
  ['prog_bar_transfer']       = 'SEIZING SUPPLIES & STOCK',
  

}
